site_name: Documentação – Projeto Eng Dados  
repo_url: https://github.com/HianRick/ProjetoEngDados  
repo_name: GitHub

theme:
  name: material
  language: pt-BR
  features:
    - navigation.top
    - content.code.copy
    - search.highlight
    - navigation.expand

nav:
  - Início: index.md
  - Requisitos: requisitos.md
  - Arquitetura do Projeto: arquitetura.md
  - Geração de Dados:
      - Biblioteca Faker: faker.md
      - Tabelas Geradas: tabelas.md
  - Database: database.md 
  - Datasets: datasets.md 
  - Notebooks: 
      - Notebooks: notebooks.md
      - Conexão: conexao.md
      - Vinhos – Parte 1: vinhos1.md
      - Vinhos – Parte 2: vinhos2.md
      - Vinhos - Parte 3: vinhos3.md
      - Vinhos - Parte 4: vinhos4.md 
  - Jobs: jobs.md 

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
